### PR TITLE
Add GH Pull Request template

### PR DESCRIPTION
**Pull request by hamen**
I would like to have this to keep a stricter discipline with my PRs, without the need of having everything in mind.

### CODE REVIEW

**Review by rock3r — COMMENTED** [review]
I'm dreading having to fill this in every time I open a PR. I understand why you want this for yourself, but is it really necessary to impose it on everyone's PRs, too?

**Comment by hamen** [comment]
I don't want to impose anything. I'm not sure what's everybody else's workflow, and I thought these would be steps useful to everybody opening PR. It's a common thing in many projects.

**Comment by rock3r** [comment]
It's just... _very_ verbose. I'd be ok with 2-3 items to check, but this is overwhelming for me. If we can slim it down a bit, I think we could ship it.

**Comment by hamen** [comment]
No worries. I'll keep it as a local personal checklist 👍🏻

**Pull request closed without merging**
